nun = int(input('Digite um número para ver sua tabuada: '))
print('-' * 12)
print('{} x {} = {}'.format(nun, 1, nun*1))
print('{} x {} = {}'.format(nun, 2, nun*2))
print('{} x {} = {}'.format(nun, 3, nun*3))
print('{} x {} = {}'.format(nun, 4, nun*4))
print('{} x {} = {}'.format(nun, 5, nun*5))
print('{} x {} = {}'.format(nun, 6, nun*6))
print('{} x {} = {}'.format(nun, 7, nun*7))
print('{} x {} = {}'.format(nun, 8, nun*8))
print('{} x {:2} = {}'.format(nun, 9, nun*9))
print('{} x {:2} = {}'.format(nun, 10, nun*10))
print('-' * 12)